// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAmCw097bcOHKfrzwLWj9q_bDD17QQWnk',
    appId: '1:987178456656:web:34fe19182a2b6fcf912355',
    messagingSenderId: '987178456656',
    projectId: 'parkshield-app',
    authDomain: 'parkshield-app.firebaseapp.com',
    storageBucket: 'parkshield-app.appspot.com',
    measurementId: 'G-D1PRFLHWQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH6InEhLJbEw1clmqpUs4LAzJJIfalSEQ',
    appId: '1:987178456656:android:6c695e033812b9c9912355',
    messagingSenderId: '987178456656',
    projectId: 'parkshield-app',
    storageBucket: 'parkshield-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPhUm9d1XEVZnFTJiO53pNqQw77iXGpTk',
    appId: '1:987178456656:ios:ca0f27977dcd8bdd912355',
    messagingSenderId: '987178456656',
    projectId: 'parkshield-app',
    storageBucket: 'parkshield-app.appspot.com',
    iosClientId:
        '987178456656-d65jt8d6det7fi0a08f173o6nvrombbg.apps.googleusercontent.com',
    iosBundleId: 'com.rushour0.parkshield',
  );
}
